name: Publish QGis plugin
'on':
  push:
    tags:
      - '*'
env:
  PROJECT_FOLDER: GeoLinesQC
  PYTHON_VERSION_RELEASE: '3.8'
  QGISPLUGINCI_VERSION: '${{ github.ref_name }}'
  PLUGIN_NAME: GeoLinesQC
jobs:
  build-python-wheel:
    name: "\U0001F40D Python Wheel"
    uses: ./.github/workflows/build.yaml
  publish-plugin:
    name: Publish plugin on tag
    runs-on: ubuntu-latest
    needs:
      - build-python-wheel
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Extract Version from Tag
        run: 'echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV'
      - name: Extract Version from Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Debug Version
        run: |
          echo "Extracted version: ${{ env.VERSION }}"
          echo "Extracted tag: ${{ env.TAG }}"
          mkdir -p dist
      - name: Retrieve Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: 'GeoLinesQC.${{ env.VERSION }}'
          path: dist
      - name: Display structure of downloaded files
        run: |
          ls -R dist
          unzip -p dist/GeoLinesQC.${{ env.VERSION }}.zip GeoLinesQC/metadata.txt  > metadata.txt
      - name: Generate plugins.xml
        run: >
          python generate_plugins_xml.py "${PLUGIN_NAME}" "${{ env.VERSION }}"
          "https://dubious.cloud"

      - name: Upload folder to bucket
        uses: a-sync/s3-uploader@master
        with:
          args: --recursive --exclude "*.log"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_KEY: 'qgis/plugins'
          FILE: './dist'

